config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/downloadFile' => 'pages#downloadFile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :creations
  resources :sites
  resources :articles
  resources :videos
  resources :contacts, only: [:new, :create]
  resources :games
  resources :parties, only: [:index, :create]
  resources :sitephotos, only: [:index, :new, :create, :destroy]
  get '/dashboard', to: 'accounts#dashboard'
  get '/newdesign', to: 'pages#newdesign'
  get '/whack_a_mole', to: 'games#whack_a_mole'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :title, uniqueness: true
end

app/models/contact.rb
class Contact < MailForm::Base
attribute :name, :validate => true
attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
attribute :message, :validate => true
attribute :nickname, :captcha => true


  def headers
    {
      :subject => "My Contact Form",
      :to => "adri.lefrancq@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/creation.rb
class Creation < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :title, uniqueness: true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/partie.rb
class Partie < ApplicationRecord
end

app/models/site.rb
class Site < ApplicationRecord
  has_many :sitephotos
  mount_uploader :photo, PhotoUploader
  validates :title, uniqueness: true
end

app/models/sitephoto.rb
class Sitephoto < ApplicationRecord
  belongs_to :site
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :title, uniqueness: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  def dashboard
    if user_signed_in?
      @sites = Site.all
      @creations = Creation.all
      @videos = Video.all
      @articles = Article.all
      @games = Game.all
    else
      redirect_to user_signed_in
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_by_id, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @articles = Article.all.sort{ |a,b| b.created_at <=> a.created_at}
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @article.update(article_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to dashboard_path
  end

  private

  def find_by_id
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :url, :photo, :photo_cache, :type, :description )
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end

  private

  # def contact_params
  #   params.require(:contact).permit(:title, :url, :photo, :photo_cache, :type, :description )
  # end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :whack_a_mole]
  before_action :find_by_id, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def whack_a_mole
    @parties_easy = Partie.where(game: "whack a mole", difficulty: "easy")
    @parties_hard = Partie.where(game: "whack a mole", difficulty: "hard")
    @parties_easy = @parties_easy.sort { |a,b| b.score <=> a.score}
    @parties_hard = @parties_hard.sort { |a,b| b.score <=> a.score}
    @parties_easy = @parties_easy.first(8)
    @parties_hard = @parties_hard.first(8)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params_games)
    if @game.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @game.update(params_games)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to dashboard_path
  end

  private

  def find_by_id
    @game = Game.find(params[:id])
  end

  def params_games
    params.require(:game).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :downloadFile, :newdesign]

  def home
  end

  def downloadFile
    send_file(
    "#{Rails.root}/public/Adrien LEFRANCQ CV.pdf",
    filename: "Adrien_Lefrancq_CV.pdf",
    type: "application/pdf"
    )
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create]

  def create
    @partie = Partie.new(params_partie)
    if @partie.save
      return true
    else
      return "Error: We couldn't save your score..."
    end
  end

  private

  def params_partie
    params.require(:partie).permit(:name, :game, :score, :difficulty)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :find_by_id, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @sites = Site.all.sort{ |a,b| b.created_at <=> a.created_at}
  end

  def show
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new(site_params)
    if @site.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @site.update(site_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @site.destroy
    redirect_to dashboard_path
  end

  private

  def find_by_id
    @site = Site.find(params[:id])
  end

  def site_params
    params.require(:site).permit(:title, :url, :photo, :photo_cache, :type, :description )
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :find_by_id, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @creativ = Video.where(collection: "Creativ Construction").sort{ |a,b| b.created_at <=> a.created_at}
    @adrien = Video.where(collection: "Adrien Lefrancq").sort{ |a,b| b.created_at <=> a.created_at}
  end

  def show
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @video.update(video_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    redirect_to dashboard_path
  end

  private

  def find_by_id
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :url, :photo, :photo_cache, :description, :collection )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # ajoutez la ligne ci-dessous pour que le helper fonctionne indifféremment
    # avec une image dans vos assets ou une url absolue
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <%= favicon_link_tag 'banner-logo.png'%>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<header class="banner-new-hom"></header>
<%= render 'shared/new-nav' %>
<div class="title-home">
  <h1>Welcome to IRDANE's portfolio</h1>
</div>
<div class="wrapper-hom">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 cole-padding">
        <%= link_to sites_path do %>
          <div class="home-card-border">
            <div class="home-inside-card">
              <div class="home-card-title">
                <h3>WEBSITES</h3>
              </div>
              <div class="home-card-description">
                <p>
                  Here you can find all my creations or projects that I worked on at school at Le Wagon or on my own.
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 cole-padding">
        <%= link_to creations_path do %>
          <div class="home-card-border">
            <div class="home-inside-card">
              <div class="home-card-title">
                <h3>GRAPHIC DESIGN</h3>
              </div>
              <div class="home-card-description">
                <p>
                  I started the graphic design as a hobby 2 years ago and step by step I improved my skills. Take a look!
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 cole-padding">
        <%= link_to games_path do %>
          <div class="home-card-border">
            <div class="home-inside-card">
              <div class="home-card-title">
                <h3>GAMES</h3>
              </div>
              <div class="home-card-description">
                <p>
                  I created some games to explore all the possibilities of JavaScript language. Have fun!
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 cole-padding">
        <%= link_to videos_path do %>
          <div class="home-card-border">
            <div class="home-inside-card">
              <div class="home-card-title">
                <h3>VIDEOS</h3>
              </div>
              <div class="home-card-description">
                <p>
                  For myself and my family I'm recording, editing and publishing videos. If you're curious and not too scared, check it out!
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 cole-padding">
        <%= link_to articles_path do %>
          <div class="home-card-border">
            <div class="home-inside-card">
              <div class="home-card-title">
                <h3>ARTICLES</h3>
              </div>
              <div class="home-card-description">
                <p>
                  I created this section for push myself to write more. And share my ideas through another media.
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/newdesign.html.erb
<header class="banner-new-hom"></header>
<%= render 'shared/new-nav' %>

app/views/pages/olddesign.html.erb
<div class="banner-home-page">
  <div class="rectangle-div">
    <div class="b-l"></div>
    <div class="b-r"></div>
    <div class="gradient-div d-flex justify-content-center">
      <div class="banner-logo"></div>
      <%= render 'shared/irdane' %>
    </div>
    <div class="banner-text">
      <h1>
        Welcome to my portfolio
      </h1>
    </div>
  </div>
</div>
<div class="wrapper-home">

  <section class="section-1 section-gauche">
    <div class="rectangle-cache"></div>
    <div class="equilibre d-flex align-items-center">
      <div>
        <div class="title">
          <h2>Websites</h2>
        </div>
        <p>
          "je peux pas êttre son portrait cracher, est ce que l'absence de modèle l'empêche d'être un papa poule , j'ai pas besoin de ça il apas besoin de ça , au final tout ce qu'il reste des sentiments gaché, constence c'est mon
        </p>
        <div class="card-btn">
          <%= link_to "See more", sites_path, class: "btn btn-home-card" %>
        </div>
      </div>
    </div>
    <div class="content">

    </div>
    <div class="imagebox">
    </div>
  </section>

  <section class="section-2 section-droit">
    <div class="imagebox">
    </div>
    <div class="rectangle-cache"></div>
    <div class="equilibre d-flex align-items-center">
      <div>
        <div class="title">
          <h2>Graphic Design</h2>
        </div>
        <p>
          "je peux pas êttre son portrait cracher, est ce que l'absence de modèle l'empêche d'être un papa poule , j'ai pas besoin de ça il apas besoin de ça , au final tout ce
        </p>
        <div class="card-btn">
          <%= link_to "See more", creations_path, class: "btn btn-home-card" %>
        </div>
      </div>
    </div>
    <div class="content">
    </div>
  </section>

</div>
<div class="contact-work">
  <div class="content">
    <div class="top-right"></div>
    <div class="top-left"></div>
    <div class="bottom-left"></div>
    <div class="bottom-right"></div>
    <div class="carre"></div>
    <div class="masque"></div>
    <div class="content-message">
      <h2>Are you interested in my work?</h2>
      <div class="choice justify-content-center">
        <div class="left">
          <%= link_to "Fiveer Page", sites_path, class: "btn btn-home-card" %>
        </div>
        <div class="right">
          <%= link_to "Autre Page", sites_path, class: "btn btn-home-card" %>
        </div>
      </div>

    </div>
  </div>
</div>
</div>
<div class="last-wrapper">
  <div class="hobbies">
    <div class="hobbies-left"></div>
    <div class="hobbies-right"></div>
      <div class="hobbiestitle">
        <h2>Hobbies</h2>
      </div>
    <div class="card-perso">
      <div class="gauche d-flex justify-content-center align-items-center">
        <div class="titre-perso">
          <h3>Videos</h3>
        </div>
        <%= link_to videos_path do %>
          <i class="fas fa-search"></i>
        <% end %>
      </div>
      <div class="droite d-flex justify-content-center align-items-center">
        <div class="titre-perso">
          <h3>Articles</h3>
        </div>
        <%= link_to articles_path do %>
          <i class="fas fa-search"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-12 col-sm-12 col-xl-3 col-lg-3 no-padding">
        <%= link_to "https://github.com/irdane21", target: :_blank do %>
          <i class="fab fa-github"></i>
        <% end %>
      </div>
      <div class="col-md-12 col-sm-12 col-xl-3 col-lg-3 no-padding">
        <%= link_to "https://www.instagram.com/irdane_21/", target: :_blank do %>
          <i class="fab fa-instagram"></i>
        <% end %>
      </div>
      <div class="col-md-12 col-sm-12 col-xl-3 col-lg-3 no-padding">
        <%= link_to "https://www.youtube.com/channel/UCddE5znXiM2pl15WUtI1_lQ", target: :_blank do %>
          <i class="fab fa-youtube"></i>
        <% end %>
      </div>
      <div class="col-md-12 col-sm-12 col-xl-3 col-lg-3 no-padding">
        <%= link_to "https://www.linkedin.com/in/adrien-lefrancq-669bb3164/", target: :_blank do %>
          <i class="fab fa-linkedin"></i>
        <% end %>
      </div>
      <div class="col-md-10 col-sm-10 col-xl-10 col-lg-10">
        <p> <%= link_to 'Download my resume', pages_downloadFile_url %></p>
      </div>
      <div class="col-md-10 col-sm-10 col-xl-10 col-lg-10">
        <p><%= link_to "Contact form", new_contact_path %></p>
      </div>
      <div class="col-md-10 col-sm-10 col-xl-10 col-lg-10">
        <p>This website is made by <%= link_to "I", dashboard_path %>rdane and inspired by Wes-Bos</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_new-nav.html.erb
<nav id="maine">
  <ul class="navbar-normal">
    <li class="pop-logo"><a href="#">IRDANE.</a></li>
    <li><a href="/">Home</a></li>
    <li><a href="/sites">Websites</a></li>
    <li><a href="/creations">Graphic Design</a></li>
    <li><a href="/games">Games</a></li>
    <li><a href="/videos">Videos</a></li>
    <li><a href="/articles">Articles</a></li>
    <li><a href="/contacts/new">Contact</a></li>
  </ul>
  <ul class="navbar-mini">
    <li class="pop-logo"><a href="#">IRDANE.</a></li>
    <li id="dropp">
      <i class="fas fa-bars mini"></i>
      <div id="myDropDownMenu" class="dropdown-content">
        <div>
          <%= link_to "Home", "/", class: "btn btn-navbar"%>
        </div>
        <div>
          <%= link_to "Websites", sites_path, class: "btn btn-navbar"%>
        </div>
        <div>
          <%= link_to "Graphic Design", creations_path, class: "btn btn-navbar"%>
        </div>
        <div>
          <%= link_to "Videos", videos_path, class: "btn btn-navbar"%>
        </div>
        <div>
          <%= link_to "Games", games_path, class: "btn btn-navbar"%>
        </div>
        <div>
          <%= link_to "Contact", new_contact_path, class: "btn btn-navbar"%>
        </div>
      </div>
    </li>
  </ul>
</nav>