config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/downloadFile' => 'pages#downloadFile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :creations
  resources :sites
  resources :articles
  resources :videos
  resources :contacts, only: [:new, :create]
  resources :games
  resources :parties, only: [:index, :create]
  resources :sitephotos, only: [:index, :new, :create, :destroy]
  get '/dashboard', to: 'accounts#dashboard'
  get '/newdesign', to: 'pages#newdesign'
  get '/whack_a_mole', to: 'games#whack_a_mole'
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :whack_a_mole]
  before_action :find_by_id, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def whack_a_mole
    @parties_easy = Partie.where(game: "whack a mole", difficulty: "easy")
    @parties_hard = Partie.where(game: "whack a mole", difficulty: "hard")
    @parties_easy = @parties_easy.sort { |a,b| b.score <=> a.score}
    @parties_hard = @parties_hard.sort { |a,b| b.score <=> a.score}
    @parties_easy = @parties_easy.first(8)
    @parties_hard = @parties_hard.first(8)
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params_games)
    if @game.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @game.update(params_games)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to dashboard_path
  end

  private

  def find_by_id
    @game = Game.find(params[:id])
  end

  def params_games
    params.require(:game).permit(:name)
  end
end

app/views/games/_form.html.erb
<%= simple_form_for @game do |f| %>
  <%= f.input :name, placeholder: @game.name %>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/games/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h2>Update <%= @game.name %></h2>
      <%= render 'form', creation: @game %>
    </div>
  </div>
</div>

app/views/games/index.html.erb
<%= render 'shared/new-nav' %>
<div class="wrapper-game">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-12 col-md-12 col-xl-9 col-lg-10">
        <div class="pompailoppe">
          <h1>Choose one game and try to beat my records!</h1>
        </div>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-12 col-sm-12 col-col-md-10 col-xl-5 col-lg-5">
        <div class="game-card-edge">
          <%= link_to whack_a_mole_path do %>
            <div class="game-card">
              <h3>Whack a mole!</h3>
              <%= image_tag("mole.svg", :class => "img-whack-a-mole") %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h2>New Game</h2>
      <%= render 'form', creation: @game %>
    </div>
  </div>
</div>

app/views/games/whack_a_mole.html.erb
<div class="wrapper d-flex no-padding">
  <div class="side-score-bar">
    <button class="startGame btn-startgame orange-color no-padding">Start!</button>
    <div class="switch-button d-flex">
      <button class="difficultybutton btn-easy btn-active">EASY</button>
      <button class="difficultybutton btn-hard">HARD</button>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Score</th>
        </tr>
      </thead>
      <tbody class="ladder-hard table-hide">
        <tr>
          <th scope="row">1</th>
          <td class="player-name">
            <%= @parties_hard[0] ? @parties_hard[0].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_hard[0] ? @parties_hard[0].score : '' %>
          </td>
        </tr>
        <tr>
          <th scope="row">2</th>
          <td class="player-name">
            <%= @parties_hard[1] ? @parties_hard[1].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_hard[1] ? @parties_hard[1].score : '' %>
          </td>
        </tr>
        <tr>
          <th scope="row">3</th>
          <td class="player-name">
            <%= @parties_hard[2] ? @parties_hard[2].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_hard[2] ? @parties_hard[2].score : '' %>
          </td>
        </tr>
        <tr>
          <th scope="row">4</th>
          <td class="player-name">
            <%= @parties_hard[3] ? @parties_hard[3].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_hard[3] ? @parties_hard[3].score : '' %>
          </td>
        </tr>
        <tr>
          <th scope="row">5</th>
          <td class="player-name">
            <%= @parties_hard[4] ? @parties_hard[4].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_hard[4] ? @parties_hard[4].score : '' %>
          </td>
        </tr>
        <tr>
          <th scope="row">6</th>
          <td class="player-name">
            <%= @parties_hard[5] ? @parties_hard[5].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_hard[5] ? @parties_hard[5].score : '' %>
          </td>
        </tr>
        </tr>
          <th scope="row">7</th>
          <td class="player-name">
            <%= @parties_hard[6] ? @parties_hard[6].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_hard[6] ? @parties_hard[6].score : '' %>
          </td>
        </tr>
        <tr>
          <th scope="row">8</th>
          <td class="player-name">
            <%= @parties_hard[7] ? @parties_hard[7].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_hard[7] ? @parties_hard[7].score : '' %>
          </td>
        </tr>
      </tbody>
      <tbody class="ladder-easy">
        <tr >
          <th scope="row">1</th>
          <td class="player-name">
            <%= @parties_easy[0] ? @parties_easy[0].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_easy[0] ? @parties_easy[0].score : '' %>
          </td>
        </tr>
        <tr >
          <th scope="row">2</th>
          <td class="player-name">
            <%= @parties_easy[1] ? @parties_easy[1].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_easy[1] ? @parties_easy[1].score : '' %>
          </td>
        </tr>

        <tr>
          <th scope="row">3</th>
          <td class="player-name">
            <%= @parties_easy[2] ? @parties_easy[2].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_easy[2] ? @parties_easy[2].score : '' %>
          </td>
        </tr>

        <tr>
          <th scope="row">4</th>
          <td class="player-name">
            <%= @parties_easy[3] ? @parties_easy[3].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_easy[3] ? @parties_easy[3].score : '' %>
          </td>
        </tr>

        <tr>
          <th scope="row">5</th>
          <td class="player-name">
            <%= @parties_easy[4] ? @parties_easy[4].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_easy[4] ? @parties_easy[4].score : '' %>
          </td>
        </tr>

        <tr>
          <th scope="row">6</th>
          <td class="player-name">
            <%= @parties_easy[5] ? @parties_easy[5].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_easy[5] ? @parties_easy[5].score : '' %>
          </td>
        </tr>

        <tr>
          <th scope="row">7</th>
          <td class="player-name">
            <%= @parties_easy[6] ? @parties_easy[6].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_easy[6] ? @parties_easy[6].score : '' %>
          </td>

        <tr>
          <th scope="row">8</th>
          <td class="player-name">
            <%= @parties_easy[7] ? @parties_easy[7].name : '' %>
          </td>
          <td class="player-score">
            <%= @parties_easy[7] ? @parties_easy[7].score : '' %>
          </td>
        </tr>
      </tbody>
    </table>
    <!-- <button class="btn-startgame other-color">Quit</button> -->
    <%= link_to games_path do %>
      <p class="btn-startgame other-color">QUIT</p>
    <% end %>
  </div>
  <div class="wrapper-mole-game">
    <h1>Whack-a-mole! <span class="score">0</span></h1>
    <div class="end-game-message">
      <h4></h4>
      <input type="text" name="name" class="end-game-input" placeholder="your pseudo">
      <button class="btn btn-success">Save it!</button>
    </div>
    <div class="game">
      <div class="hole hole1">
        <div class="mole mole1"></div>
      </div>
      <div class="hole hole2 hole-easy">
        <div class="mole mole2"></div>
      </div>
      <div class="hole hole3 hole-easy">
        <div class="mole mole3"></div>
      </div>
      <div class="hole hole4 hole-easy">
        <div class="mole mole4"></div>
      </div>
      <div class="hole hole5">
        <div class="mole mole5"></div>
      </div>
      <div class="hole hole6">
        <div class="mole mole6"></div>
      </div>
      <div class="hole hole7 hole-easy">
        <div class="mole mole7"></div>
      </div>
      <div class="hole hole8 hole-easy">
        <div class="mole mole8"></div>
      </div>
      <div class="hole hole9 hole-easy">
        <div class="mole mole9"></div>
      </div>
      <div class="hole hole10">
        <div class="mole mole10"></div>
      </div>
      <div class="hole hole11">
        <div class="mole mole11"></div>
      </div>
      <div class="hole hole12 hole-easy">
        <div class="mole mole12"></div>
      </div>
      <div class="hole hole13 hole-easy">
        <div class="mole mole13"></div>
      </div>
      <div class="hole hole14 hole-easy">
        <div class="mole mole14"></div>
      </div>
      <div class="hole hole15">
        <div class="mole mole15"></div>
      </div>
    </div>
  </div>
</div>