config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/downloadFile' => 'pages#downloadFile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :creations
  resources :sites
  resources :articles
  resources :videos
  resources :contacts, only: [:new, :create]
  resources :games
  resources :parties, only: [:index, :create]
  resources :sitephotos, only: [:index, :new, :create, :destroy]
  get '/dashboard', to: 'accounts#dashboard'
  get '/newdesign', to: 'pages#newdesign'
  get '/whack_a_mole', to: 'games#whack_a_mole'
end

app/models/sitephoto.rb
class Sitephoto < ApplicationRecord
  belongs_to :site
  mount_uploader :photo, PhotoUploader
end

app/controllers/sitephotos_controller.rb
class SitephotosController < ApplicationController

  def index
    @sitephotos = Sitephoto.where(site_id: params[:id])
    @site = Site.find(params[:id])
  end

  def new
    @sitephoto = Sitephoto.new
    @site = Site.find(params[:id])
  end

  def create
    @sitephoto = Sitephoto.new(sitephoto_params)
    if @sitephoto.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    @sitephoto = Sitephoto.find(params[:id])
    @sitephoto.destroy
    redirect_to dashboard_path
  end

  private

  def sitephoto_params
    params.require(:sitephoto).permit(:photo, :photo_cache, :site_id)
  end

end

app/views/sitephotos/index.html.erb
<div class="container padding">
  <ul>
    <% @sitephotos.each do |photo| %>
      <li>
        <%= cl_image_tag(photo.photo, class: 'avatar',
                width: 150, height: 150, crop: :thumb, gravity: :face) %>
        <%= link_to "Delete", sitephoto_path(photo.id), :method => :delete, data: {:confirm => "You sure?" }, class:"btn btn-danger" %>
      </li>
    <% end %>
  </ul>
  <%= link_to "Add a photo", new_sitephoto_path(:id => @site.id), class:"btn btn-success" %>
</div>

app/views/sitephotos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h3>Add some photo to this project ? </h3>
      <%= simple_form_for @sitephoto do |f| %>
        <%= f.input :site_id, as: :hidden, input_html: {value: @site.id} %>
        <%= f.input :photo %>
        <%= f.error_notification message: 'Something went wrong' %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>