config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'pages/downloadFile' => 'pages#downloadFile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :creations
  resources :sites
  resources :articles
  resources :videos
  resources :contacts, only: [:new, :create]
  resources :games
  resources :parties, only: [:index, :create]
  resources :sitephotos, only: [:index, :new, :create, :destroy]
  get '/dashboard', to: 'accounts#dashboard'
  get '/newdesign', to: 'pages#newdesign'
  get '/whack_a_mole', to: 'games#whack_a_mole'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  def dashboard
    if user_signed_in?
      @sites = Site.all
      @creations = Creation.all
      @videos = Video.all
      @articles = Article.all
      @games = Game.all
    else
      redirect_to user_signed_in
    end
  end

end

app/views/accounts/dashboard.html.erb
<div class="wrapper-dash">
  <div class="container">
  <% if current_user.admin? %>
    <div class="d-flex justify-content-center">
      <h2> Welcome Adrien! </h2>
    </div>
    <div class="dashboard-card ">
      <h3> Add a new creation:</h3>
      <div class="row">
        <div class="col">
          <div class="d-flex justify-content-center">
            <div class="button">
              <%= link_to "Web Site", new_site_path, class:"btn btn-success" %>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="d-flex justify-content-center">
            <div class="button">
              <%= link_to "Graphic Design", new_creation_path, class:"btn btn-success" %>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="d-flex justify-content-center">
            <div class="button">
              <%= link_to "Video", new_video_path, class:"btn btn-success" %>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="d-flex justify-content-center">
            <div class="button">
              <%= link_to "Article", new_article_path, class:"btn btn-success" %>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="d-flex justify-content-center">
            <div class="button">
              <%= link_to "Game", new_game_path, class:"btn btn-success" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="dashboard-card">
      <h3> Modify a creation: </h3>
      <div class="row">
        <h4> The web sites : </h4>
        <div class="col anotherclassforstyle-left">
          <ul class="trip-creator-col">
            <% @sites.each do |site| %>
              <li class="d-flex justify-content-around item">
                <div class="profil_avatar_photo">
                  <%= cl_image_tag(site.photo, class: 'avatar',
                  width: 150, height: 150, crop: :thumb, gravity: :face) %>
                </div>
                <p class="d-flex align-items-center"><%= site.title %></p>
                <%= link_to "photo", sitephotos_path(:id => site.id), class:"btn btn-primary size" %>
                <%= link_to "Update", edit_site_path(site.id), class:"btn btn-warning size" %>
                <%= link_to "Delete", site_path(site.id), :method => :delete, data: {:confirm => "You sure?" }, class:"btn btn-danger size" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="row">
        <h4> The creations : </h4>
        <div class="col anotherclassforstyle-left">
          <ul class="trip-creator-col">
            <% @creations.each do |creation| %>
              <li class="d-flex justify-content-around item">
                <div class="profil_avatar_photo">
                  <%= cl_image_tag(creation.photo, class: 'avatar',
                  width: 150, height: 150, crop: :thumb, gravity: :face) %>
                </div>
                <p class="d-flex align-items-center"><%= creation.title %></p>
                <%= link_to "Update", edit_creation_path(creation.id), class:"btn btn-warning size" %>
                <%= link_to "Delete", creation_path(creation.id), :method => :delete, data: {:confirm => "You sure?" }, class:"btn btn-danger size" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="row">
        <h4> The videos : </h4>
        <div class="col anotherclassforstyle-left">
          <ul class="trip-creator-col">
            <% @videos.each do |video| %>
              <li class="d-flex justify-content-around item">
                <div class="profil_avatar_photo">
                  <%= cl_image_tag(video.photo, class: 'avatar',
                  width: 150, height: 150, crop: :thumb, gravity: :face) %>
                </div>
                <p class="d-flex align-items-center"><%= video.title %></p>
                <%= link_to "Update", edit_video_path(video.id), class:"btn btn-warning size" %>
                <%= link_to "Delete", video_path(video.id), :method => :delete, data: {:confirm => "You sure?" }, class:"btn btn-danger size" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="row">
        <h4> The articles : </h4>
        <div class="col anotherclassforstyle-left">
          <ul class="trip-creator-col">
            <% @articles.each do |article| %>
              <li class="d-flex justify-content-around item">
                <div class="profil_avatar_photo">
                  <%= cl_image_tag(article.photo, class: 'avatar',
                  width: 150, height: 150, crop: :thumb, gravity: :face) %>
                </div>
                <p class="d-flex align-items-center"><%= article.title %></p>
                <%= link_to "Update", edit_article_path(article.id), class:"btn btn-warning size" %>
                <%= link_to "Delete", articles_path(article.id), :method => :delete, data: {:confirm => "You sure?" }, class:"btn btn-danger size" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="row">
        <h4> The games : </h4>
        <div class="col anotherclassforstyle-left">
          <ul class="trip-creator-col">
            <% @games.each do |game| %>
              <li class="d-flex justify-content-around item">
                <p class="d-flex align-items-center"><%= game.name %></p>
                <%= link_to "Update", edit_game_path(game.id), class:"btn btn-warning size" %>
                <%= link_to "Delete", game_path(game.id), :method => :delete, data: {:confirm => "You sure?" }, class:"btn btn-danger size" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %>
    </div>
  <% else  %>

    <h2> Oups! there is nothing for you here...</h2>

  <% end %>

  </div>
</div>